### ISSUE TITLE
PHP 5.5 compat

### ISSUE THREAD

**Issue by Krinkle** [ramsey/pygments#2]
Hi @ramsey,

Before I can consider updating Wikimedia's use of Pygments.php in [mediawiki](https://github.com/wikimedia/mediawiki), the package would first need to [support PHP 5.5.9](https://www.mediawiki.org/wiki/Compatibility#PHP).

The main reason we haven't dropped support for PHP 5.5 yet (despite it [being](https://secure.php.net/supported-versions.php) [eol](https://secure.php.net/eol.php) since July 2016), is for compatibility with the Ubuntu Trusty release channel, this LTS started in 2014 and won't end until April 2019.

<http://packages.ubuntu.com/trusty/php5>
<https://wiki.ubuntu.com/Releases>

**Comment by ramsey** [comment]
Yikes! By April 2019, 5.6 and 7.0 will be EOL and 7.1 will be in "security fixes only" state. https://php.net/supported-versions.php

It shouldn't be hard to do a 1.0.1 release for 5.5 support, though. I'll see what I can whip up quickly.

Thanks!

**Comment by Krinkle** [comment]
@ramsey Yeah, the only good news is that the next Ubuntu LTS (Ubuntu 16 Xenial) jumps straight to PHP 7 (<http://packages.ubuntu.com/xenial/php/php>).

**Comment by ramsey** [comment]
I released 1.0.1, which supports PHP 5.5.9 and greater. Let me know if you have any issues with it. Thanks!
